spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      label: master
      #fail-fast: true
  profiles:
    active: development
