spring:
  application:
    name: discovery-server
  config:
    import: optional:configserver:http://localhost:8888,optional:configserver:http://localhost:8889
  cloud:
    config:
      label: stock-analyzer
      #fail-fast: true
  profiles:
    active: development
