server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://https://github.com/MichaelWojda/StockAnalyzer/configurations
          search-paths: configuration-files
          try-master-branch: false
