server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MichaelWojda/StockAnalyzer
          search-paths: configurations
          try-master-branch: false
